package com.provasoap.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServiceImpl", targetNamespace = "http://service.provasoap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<cm2.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.provasoap.com/", className = "com.provasoap.service.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.provasoap.com/", className = "com.provasoap.service.GetAllResponse")
    @Action(input = "http://service.provasoap.com/EmployeeServiceImpl/getAllRequest", output = "http://service.provasoap.com/EmployeeServiceImpl/getAllResponse")
    public List<Employee> getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns cm2.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://service.provasoap.com/", className = "com.provasoap.service.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://service.provasoap.com/", className = "com.provasoap.service.GetEmployeeByIdResponse")
    @Action(input = "http://service.provasoap.com/EmployeeServiceImpl/getEmployeeByIdRequest", output = "http://service.provasoap.com/EmployeeServiceImpl/getEmployeeByIdResponse")
    public Employee getEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://service.provasoap.com/", className = "com.provasoap.service.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://service.provasoap.com/", className = "com.provasoap.service.AddEmployeeResponse")
    @Action(input = "http://service.provasoap.com/EmployeeServiceImpl/addEmployeeRequest", output = "http://service.provasoap.com/EmployeeServiceImpl/addEmployeeResponse")
    public void addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://service.provasoap.com/", className = "com.provasoap.service.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://service.provasoap.com/", className = "com.provasoap.service.DeleteEmployeeResponse")
    @Action(input = "http://service.provasoap.com/EmployeeServiceImpl/deleteEmployeeRequest", output = "http://service.provasoap.com/EmployeeServiceImpl/deleteEmployeeResponse")
    public String deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
